services:
  - type: web
    name: aethermind-bot            # 服务名，想改可改为你的
    env: node
    plan: starter                   # 需要更大可改 standard
    autoDeploy: true
    buildCommand: npm install --include=dev --ignore-scripts && npm run build
    startCommand: npm start
    healthCheckPath: /healthz

    # 持久化：挂载 /data，用于 SQLite 文件
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

    envVars:
      # 机密（在 Render 控制台填写），不会被仓库值覆盖
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FORWARD_TARGET_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      # 可选机密
      - key: REVIEW_TARGET_ID
        sync: false
      - key: WELCOME_TEXT
        sync: false

      # 运行时参数
      - key: NODE_VERSION
        value: 20.10.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=512

      # 业务可选
      - key: ATTACH_BUTTONS_TO_TARGET_META
        value: "1"
      - key: PER_USER_COOLDOWN_MS
        value: "3000"
      - key: GLOBAL_MIN_TIME_MS
        value: "60"

      # —— 存储选 SQLite ——（重点）
      - key: PERSIST_BACKEND
        value: sqlite
      - key: SQLITE_PATH
        value: /data/bot.db
