services:
  - type: web
    name: sh-bot
    env: node
    repo: https://github.com/Jack123-UU/sh_bot.git
    branch: feat/mod-forward-bot   # ← 部署这个分支
    region: oregon
    plan: starter                  # 或 standard，按你账户来
    numInstances: 1
    healthCheckPath: /healthz

    buildCommand: npm ci && npm run build
    startCommand: npm run start

    envVars:
      # —— Node 版本（Render 官方 Node 环境）
      - key: NODE_VERSION
        value: 20.10.0

      # —— 机器人必须
      - key: TELEGRAM_BOT_TOKEN
        sync: false               # 到 Render Dashboard 里填
      - key: FORWARD_TARGET_ID
        sync: false               # 目标频道ID（负数开头）
      - key: ADMIN_IDS
        sync: false               # 管理员用户ID，逗号分隔

      # —— 可选：统一审核频道 / 欢迎语 / 附带按钮 / 速率
      - key: REVIEW_TARGET_ID
        sync: false               # 审核频道ID；不设则逐个发管理员
      - key: WELCOME_TEXT
        sync: false
      - key: ATTACH_BUTTONS_TO_TARGET_META
        value: "1"                # 1=转发后附带导航按钮说明
      - key: PER_USER_COOLDOWN_MS
        value: "3000"
      - key: GLOBAL_MIN_TIME_MS
        value: "60"

      # —— 可选：Webhook（不填则使用轮询）
      - key: WEBHOOK_URL
        sync: false               # 例：https://你的服务名.onrender.com

      # —— 持久化（二选一，默认 Redis）
      - key: PERSIST_BACKEND
        value: redis              # 改成 sqlite 则用下方磁盘+SQLITE_PATH

      # Redis 方案（推荐：无需磁盘）
      - key: REDIS_URL
        sync: false               # 例：redis://user:pass@host:6379/0

      # SQLite 方案（仅当 PERSIST_BACKEND=sqlite 时生效）
      - key: SQLITE_PATH
        value: /data/bot.db       # 需要下面的磁盘挂载

    # SQLite 才需要的磁盘；即使用 Redis，保留也不影响（只是闲置）
    disks:
      - name: botdata
        mountPath: /data
        sizeGB: 1
