# AetherMind Technologies LLC - Render Deployment Configuration
# =============================================================
# This file configures automatic deployment on Render.com
# Documentation: https://render.com/docs/blueprint-spec

services:
  # Main Application Service
  - type: web
    name: aethermind-bot
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm install --include=dev --ignore-scripts && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.9.0"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_ADMIN_USERS
        sync: false
      - key: TELEGRAM_BOT_ENABLED
        value: "true"
      - key: TELEGRAM_BOT_RATE_LIMIT
        value: "30"
      - key: API_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: aethermind-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: aethermind-redis
          property: connectionString
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: APP_PORT
        value: "8080"
      - key: MASTRA_API_URL
        value: http://localhost:4111
      - key: INNGEST_API_PORT
        value: "3100"
      - key: RATE_LIMIT_PER_MINUTE
        value: "120"
    healthCheckPath: /health
    autoDeploy: true

  # Redis Cache Service
  - type: redis
    name: aethermind-redis
    region: oregon
    plan: standard
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

# Database Service
databases:
  - name: aethermind-db
    databaseName: aethermind_bot
    region: oregon
    plan: basic-1gb
    postgresMajorVersion: "15"