services:
  - type: web
    name: aethermind-bot
    runtime: node
    region: oregon
    plan: starter
    buildCommand: npm ci --ignore-scripts && npm run build
    startCommand: node .mastra/output/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20.9.0"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_ADMIN_USERS
        sync: false
      - key: TELEGRAM_BOT_ENABLED
        value: "true"
      - key: LOG_LEVEL
        value: info
      - key: LOG_FORMAT
        value: json
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: aethermind-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: aethermind-redis
          property: connectionString
    healthCheckPath: /api
    autoDeploy: true

  - type: postgres
    name: aethermind-db
    plan: starter

  - type: redis
    name: aethermind-redis
    plan: starter
